### ISSUE TITLE
How do the services communicate with each other ?

### ISSUE THREAD

**Issue by peterfebin** [h4xr/todo#1]
I believe at this point they still behave as two standalone applications. 
One runs on localhost:5000 and the other on localhost:5001. 
While building a microservice architecture, I would want all my services to accessible  from a single port (with the end points of all the services mounted at one place)
Would you be knowing how to accomplish that ?

**Comment by h4xr** [comment]
Hello @peterfebin

Yes, as far as this repository is concerned, the two services behave as independent services which communicate with each other through the APIs.

Now regarding your question how to make the services accessible from a single port, what you can implement is an API Gateway, which listens to the requests on a single port and forward the incoming requests to the individual services(running on their respective ports)
For this API Gateway to work, it should know, where your individual services are running and which protocol they talk.

There was an recent effort I put together https://github.com/microreg which aims to build an API Gateway and a service registry through which a user can communicate with all the Microservices through a single point of reference.

Some of the articles which you may find useful for your use case:
http://microservices.io/patterns/apigateway.html
https://smartbear.com/learn/api-design/api-gateways-in-microservices/

**Comment by peterfebin** [comment]
Great! Thanks @h4xr .

**Comment by peterfebin** [comment]
Thank you so much @h4xr . I was looking for a simple explanation on Microservices using Python and your code has helped me understand that.
